# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "client" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"address" VARCHAR NOT NULL,"postalCode" VARCHAR NOT NULL,"city" VARCHAR NOT NULL);

# --- !Downs

drop table "client";

